<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframeResult</name>
   <tag></tag>
   <elementGuidId>7d00eb9a-c922-44ce-9b9e-f8aa6eb1aba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f1583d1f-a272-4a0d-b7d4-27f2422f6a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d8183df-8acf-49f1-84f9-3a3c912479ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>e8b1d4a5-5fcd-447f-a5ee-baaaafb121fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>c7f0bba1-616a-4c78-9f62-238379bf04aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07c622b3-8a1a-431f-a44c-eba55fceb3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeResult&quot;)</value>
      <webElementGuid>388be1ed-f949-4034-a701-dca4fb696479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeResult']</value>
      <webElementGuid>d92949c8-c068-4a12-9c06-9f028717d9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframewrapper']/iframe</value>
      <webElementGuid>19900f4f-41e4-46fa-b42c-314e3d569918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/iframe</value>
      <webElementGuid>254a7f23-0b90-4393-9745-57ffa3842623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeResult' and @name = 'iframeResult']</value>
      <webElementGuid>bff30a72-199e-42de-afb7-3c4e4eca53f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
