name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clean Git Repository # Added step
      run: git clean -fdx
    - name: Katalon Studio
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '10.2.2'
          projectPath: '${{ github.workspace }}'
          args: >
            -noSplash -retry=0
            -testSuitePath="Test Suites/LoginSuite2/LoginToCura2"
            -browserType="Chrome"
            -executionProfile="QA"
            -apiKey=${{ secrets.KATALON_API_KEY }}
            --config -webui.autoUpdateDrivers=true
            -proxy.auth.option=NO_PROXY
            -proxy.system.option=NO_PROXY
            -proxy.system.applyToDesiredCapabilities=true
# Make sure this step is IDENTICALLY copied and correctly indented
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: katalon-test-reports
        path: ${{ github.workspace }}/Reports/**/*
        retention-days: 1 # Keep artifacts for 1 day to save storage
        
    - name: Download Reports for Email # New step to download the artifact back
      uses: actions/download-artifact@v4
      with:
        name: katalon-test-reports # Must match the 'name' from upload-artifact
        path: downloaded-reports # Directory where artifacts will be downloaded
        
    - name: Send Email with Report
      # This action allows sending emails with attachments
      uses: dawidd6/action-send-mail@v3 # Using v3, check marketplace for latest stable
      with:
        # SMTP server settings
        server_address: smtp.gmail.com # Example for Gmail, change for your email provider
        server_port: 465 # Example for Gmail, usually 465 for SSL or 587 for TLS
        secure: true # Use SSL/TLS
        username: ${{ secrets.EMAIL_USERNAME }} # Your email address (as a GitHub Secret)
        password: ${{ secrets.EMAIL_PASSWORD }} # App password/token (as a GitHub Secret)
        
        # Email content
        subject: "Katalon CI Report - ${{ github.workflow }} - ${{ github.ref }}"
        to: ${{ secrets.EMAIL_USERNAME }} # Replace with your actual email address
        from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}> # Optional: custom 'from' name
        
        # Attach the HTML report
        # The path should be relative to the 'downloaded-reports' directory
        # You'll need to find the exact path of the HTML report within the downloaded artifact
        attachments: "downloaded-reports/Reports/**/*.html" # This pattern should find report.html
