name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clean Git Repository # Added step
      run: git clean -fdx
    - name: Katalon Studio
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '10.2.2'
          projectPath: '${{ github.workspace }}'
          args: >
            -noSplash -retry=0
            -testSuitePath="Test Suites/LoginSuite2/LoginToCura2"
            -browserType="Chrome"
            -executionProfile="QA"
            -apiKey=${{ secrets.KATALON_API_KEY }}
            --config -webui.autoUpdateDrivers=true
            -proxy.auth.option=NO_PROXY
            -proxy.system.option=NO_PROXY
            -proxy.system.applyToDesiredCapabilities=true
# Make sure this step is IDENTICALLY copied and correctly indented
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: katalon-test-reports
        path: ${{ github.workspace }}/Reports/**/*
